

_app_contacts_directory_list:
    path: /contacts-directory
    defaults: { _controller: app.contactsDirectory.controller:listAction }
    #resource: "@ContactsDirectoryBundle/Controller/ContactsDirectoryController.php"
    #type:     annotation

_app_contacts_directory_save_order:
    path: /contacts-directory/save-order
    defaults: { _controller: app.contactsDirectory.controller:saveOrderAction }
    #requirements:
    #    _method: POST

_app_contacts_directory_add:
    path: /contacts-directory/add
    defaults: { _controller: app.contactsDirectory.controller:addAction }