
services:
    app.contactsDirectory.controller:
        class: App\ContactsDirectoryBundle\Controller\ContactsDirectoryController
        arguments: ["@contactsData"]

    contactsData:
        class: App\ContactsDirectoryBundle\Data\ContactsData
        arguments: ["@doctrine.orm.entity_manager"]